### ISSUE TITLE
Connection Closed by PictoBot?

### ISSUE THREAD

**Issue by Cuphead74832** [ayunami2000/ayunpictojava#19]
Hey i been using PictoBot (the tool that you recommended me to print images) i been using for a while in pict.chat but when i wanted to use It on my local Server. I drop an image, hit SEND, connection Closed. Happens on my local Server and not in the public Server and i like that tool you can SEND images and adjust THEM without the discord integration. So any fixes?? (Also 2nd question: I see you updated discord image quality but is It for the images that the bot sends to discord or the images that you SEND from discord over to pictochat? Also Saw the commit of settings.json whats the highest quality value?)

UPDATE: After i updated the server the tool does no longer disconnects me but when i try to do it when connected via my domain it does no let me i tried 2 domain hosters, question number 2 still not resolved

**Comment by ayunami2000** [comment]
1) intentional feature, you are sending too many lines in your drawing and it is disconnecting you as a security measure
2) allows things like this to show in the discord side (this image is from the discord side; previously, it would've been a mostly solid black square)
![SmartSelect_20240510_102514.jpg](https://github.com/ayunami2000/ayunpictojava/assets/24785136/3d26096e-d04b-4e44-b27a-ffda8fae0102)
